//
//  main.m
//  ProjectEuler002
//
//  Created by Robert Jan Bruinier on 4/6/12.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//

//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#import <Foundation/Foundation.h>

int main (int argc, const char * argv[])
{
    // solution 01
    unsigned long oldFibo = 1;    
    unsigned long fibo = 1;
    
    unsigned long sum = 0;
    
    while (fibo < 4000000)
    {
        NSLog(@"%lu", fibo);
        
        if ((fibo % 2) == 0)
        {
            sum += fibo;
        }

        unsigned long temp = fibo;

        fibo += oldFibo;
        
        oldFibo = temp;
        
    }
    
    NSLog(@"Solution #1: %lu", sum);
    
    return 0;
}

